name: Run Tests

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"

jobs:
  run-tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      # Setting fail-fast to false, will let all concurrent jobs run if one of them fails, instead of cancelling all
      # of them as soon as one fails.
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
        include:
          - os: "ubuntu-latest"
          # There is no build for Python 3.6 in ubuntu>20.04.
          # This unclude can be removed when we drop support for Python 3.6.
          - os: "ubuntu-20.04"
            python-version: "3.6"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest
